package(default_visibility = ["//visibility:private"])

licenses(["notice"])

filegroup(
    name = "ignore_srcs",
    srcs = [
        "download.py",
        "plot_ls_q.py",
        "plot_partition.py",
        "plots_for_slides.py",
        "rdp_bucketized.py",
        "rdp_cumulative.py",
        "smooth_sensitivity_table.py",
        "utility_queries_answered.py",
    ],
    tags = ["ignore_srcs"],
)
