package(default_visibility = ["//visibility:private"])

licenses(["notice"])

filegroup(
    name = "ignore_srcs",
    srcs = [
        "__init__.py",
        "losses.py",
        "losses_test.py",
        "models.py",
        "models_test.py",
        "optimizers.py",
        "optimizers_test.py",
    ],
    tags = ["ignore_srcs"],
)
