load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:private"])

licenses(["notice"])

py_library(
    name = "privacy_tests",
    srcs = ["__init__.py"],
)
