package(
    default_applicable_licenses = ["//third_party/py/tensorflow_privacy:license"],
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])

py_library(
    name = "privacy",
    srcs = ["__init__.py"],
)
