package(default_visibility = ["//visibility:private"])

licenses(["notice"])

filegroup(
    name = "ignore_srcs",
    srcs = [
        "adult_tutorial.py",
        "imdb_tutorial.py",
    ],
    tags = ["ignore_srcs"],
)
