package(default_visibility = ["//visibility:private"])

licenses(["notice"])

filegroup(
    name = "ignore_srcs",
    srcs = [
        "core.py",
        "core_test.py",
        "smooth_sensitivity.py",
        "smooth_sensitivity_test.py",
    ],
    tags = ["ignore_srcs"],
)
