package(default_visibility = ["//visibility:public"])

licenses(["notice"])

py_library(
    name = "type_aliases",
    srcs = ["type_aliases.py"],
)

py_library(
    name = "layer_registry",
    srcs = ["layer_registry.py"],
    deps = [":type_aliases"],
)
